##### gtrl Config #####
---
##### DRL #####
VIS_SENSOR : 'fish_image' # image or fish_image or depth_image 
LATENT_FEATURES_SIZE : 64  #Choisir entre 16 32 64 ou autre
#(you must modify the robot descrition file we can't have noise image with the depth image)
SEED : 3407  # Random seed number
DESC : '98' # describe what are you dowing ''newR : Rcol=-80 Rtar=120'' 
MAX_STEPS : 800 # 300
MAX_EPISODES : 800   # 500 Maximum number of steps to perform
BATCH_SIZE : 32  # Size of the mini-batch
LR_A : 0.001 # Actor learning rate
LR_C : 0.001 # Critic learning rate
GAMMA : 0.999  # Discount factor to calculate the discounted future reward (should be close to 1)
TAU : 0.0005  # Soft target update variable (should be close to 0)
ACTOR_FREQ : 1  # Frequency of Actor network updates
BUFFER_SIZE : 30000  # 2e5 Maximum size of the buffer 5500
FRAME_STACK : 4 # Number of Channel
PLOT_INTERVAL : 10
EVAL_THRESHOLD : 80 # episode trigger for evaluation
EVAL_EPOCH : 5  # number of episodes for evaluation
SAVE_INTERVAL : 50
SAVE_THRESHOLD : 1 # episode trigger for saving the model
REWARD_THRESHOLD : 90 # reward trigger for evaluation
SAVE : True # whether to save the model or not

###### Attention #####
PRE_TRAIN : True # whether intialize with pre-trained parameter
IF_TEST : False # whether testing the pre-trained parameter
ATTENTION_ONLY : True
P_ATTENTION_FIX : False # whether fix the weights and bias of transformer
C_ATTENTION_FIX : False # # whether fix the weights and bias of transformer

###### Human Intervention #####
PRE_BUFFER : True # Human expert buffer
HUMAN_INTERVENTION : False # whether need guidance from human driver

##### Entropy #####
AUTO_TUNE : True # whether automatically tune the temperature parameter
ALPHA : 1.0
LR_ALPHA : 0.0001

##### Environment #####
ENV_NAME : "RRC"
DRIVER : 'Oscar'
ROBOT : 'scout'
L_SCALE : 0.25
A_SCALE : 1.0 #2.0

##### Algo ######
SAC:
    name : 'drl'
    actor_type : "GaussianConvNet"
    critic_type : "CNN" # CNN or Transformer
    block : 0
    head : 0

GoT-SAC:
    name : 'gtrl'
    actor_type : "GaussianTransformer" # GaussianTransformer Deterministic DeterministicTransformer
    critic_type : "CNN" # CNN or Transformer
    block : 4
    head : 4